[package]
name = "dll_test_crate"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
main_thread = {path = ".."}

[dev-dependencies]
libloading = "=0.8.9"# Do not update, the latest version doesn't work on GitHub action's openbsd yet because their rustc is too old.

