[package]
name = "dll_test_crate"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
main_thread = {path = ".."}
#is_main_thread = "0.1.0"

[dev-dependencies]
libloading = "=0.8.9"# Do not update
